# depth of UNet 
depth : 3
lr : 0.000006481460531048047
epochs : 20000       
batch_size : 35 
checkpoint_path : '/home/joe/Desktop/unet/UNet-based-Denoising-Autoencoder-In-PyTorch/wandb/run-20230216_011436-2hrwqvnp/files/checkpoints/best.pt'
hidden_dim : 30
